### ISSUE TITLE
Loading times

### ISSUE THREAD

**Issue by orangebirddave** [CookiePLMonster/SilentPatchYRC#1]
Loading times in Yakuza 3 are greatly increased after installing the patch, going in and out of shops take almost a minute, while without the patch its 5 seconds max.

My specs for reference

**Operating System**
	Windows 10 Pro 64-bit
**CPU**
	Intel Core i5 3470 @ 3.20GHz	67 °C
	Ivy Bridge 22nm Technology
**RAM**
	8,00GB Dual-Channel DDR3 @ 799MHz (10-10-10-30)
**Motherboard**
	ASUSTeK COMPUTER INC. H61M-PRO (LGA1155)	35 °C
**Graphics**
	VX2457 (1920x1080@75Hz)
	Generic PnP Monitor (1280x1024@75Hz)
	2047MB NVIDIA GeForce GTX 750 Ti (MSI)	54 °C
**Storage**
	465GB SAMSUNG HD502HI (SATA )	28 °C
	931GB Seagate ST1000DM010-2EP102 (SATA )	35 °C
	232GB Samsung SSD 850 EVO 250GB (SATA (SSD))	39 °C

**Comment by CookiePLMonster** [comment]
Longer loading times are expected (I need to mention it on the mod page), but a minute sounds wrong. I'll need to look into it.

**Comment by ghost** [comment]
droppin a line to say that I have the same issue on boot up/in between zones, about a minute of black screen on launch, and now loading lasts about a full minute. 

Win10 Pro
Ryzen 9 3900X
32GB 3200mhz 
Asus Strix 2080
Asus Strix-E x570

**Comment by CookiePLMonster** [comment]
Build 2 cuts down on the CPU usage fixes I made, and therefore loading times are now back to normal.
