### ISSUE TITLE
Game very slow

### ISSUE THREAD

**Issue by ThunderHR** [CookiePLMonster/SilentPatchYRC#2]
Hi, i downloaded your fix but now in Yakuza 4 the game is very slow
Not laggy but all is like at 50%

Thanks for your help !

**Comment by CookiePLMonster** [comment]
Does this still happen with a newly released Build 2? In theory it is unlikely to, but I'd like to make sure.

**Comment by CookiePLMonster** [comment]
I have not heard a single report about slowdown with the Build 2 yet, and on paper it should be impossible to happen (unlike with the Build 1), so I am going to go ahead and close this issue.

Please reopen if it's still the cause (unlikely).
